name: Daily Commit

on:
  schedule:
    - cron: "0 12 * * *" # كل يوم 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          date >> daily.log

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily commit $(date)" || echo "No changes"
          git push
